const MutationTypes = {
  UPDATES: {
    GAUGE: 'GAUGE',
    MAKER: 'MAKER',
    MAKER_NAME: 'MAKER_NAME',
    PRODUCT_TYPE: 'PRODUCT_TYPE',
    RAILWAY_COMPANY_AREA: 'RAILWAY_COMPANY_AREA',
    RAILWAY_COMPANY_NUM: 'RAILWAY_COMPANY',
    RAILWAY_COMPANY_NAME: 'RAILWAY_COMPANY_NAME',
    SERIES: 'SERIES',
    PRODUCT_VALUE: 'PRODUCT_VALUE',
    NUMBER_OF: 'NUMBER_OF',
    DETAILS: {
      COUPLER: 'COUPLER',
      LIGHTS: 'LIGHTS',
      OPTIONS: 'OPTIONS',
      PANTOGRAPH: 'PANTOGRAPH',
      RUNNING: 'RUNNING',
      IMAGE_URL: 'IMAGE_URL'
    },
    DELIVER: {
      COMPANY: 'COMPANY',
      NAME: 'NAME',
      VALUE: 'VALUE'
    }
  }
}

export default MutationTypes
