const MutationTypes = {
  UPDATES: {
    GAUGE: 'GAUGE',
    MAKER: 'MAKER',
    MAKER_NAME: 'MAKER_NAME',
    PRODUCT_TYPE: 'PRODUCT_TYPE',
    RAILWAY_COMPANY: 'RAILWAY_COMPANY',
    RAILWAY_COMPANY_NAME: 'RAILWAY_COMPANY_NAME',
    SERIES: 'SERIES'
  }
}

export default MutationTypes
